---
- name: reload firewalld
  command: firewall-cmd --reload

- name: service Restart prometheus server
  service:
    name: prometheus
    state: restarted
  when:
   - "'service' not in ansible_skip_tags"
   - (start_services | bool)

